//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiThucHanh
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanpham
    {
        public int masp { get; set; }
        public string tensp { get; set; }
        public Nullable<decimal> dongia { get; set; }
        public string madm { get; set; }
    
        public virtual danhmuc danhmuc { get; set; }
    }
}
